
version: "3.9"

services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      auth_v1 : 
        condition : service_healthy  
      auth_v2 : 
        condition : service_healthy 
      notes_v1 : 
        condition : service_healthy 
      notes_v2 : 
        condition : service_healthy 
      assets : 
        condition : service_healthy 

    healthcheck:
      test: ["CMD", "python", "-c", "import sys, urllib.request; sys.exit(0) if urllib.request.urlopen('http://localhost/health').status==200 else sys.exit(1)"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s




  # --------------------
  # AUTH SERVICE
  # --------------------
  auth_v1:
    build: ./auth
    container_name: auth_v1
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, urllib.request; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/health').status==200 else sys.exit(1)"]
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on : 
      - postgres 


  auth_v2:
    build: ./auth
    container_name: auth_v2
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, urllib.request; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/health').status==200 else sys.exit(1)"]
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on : 
      postgres : 
        condition : service_healthy 


  # --------------------
  # NOTES SERVICE
  # --------------------
  notes_v1:
    build: ./notes
    container_name: notes_v1
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, urllib.request; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/health').status==200 else sys.exit(1)"]
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on : 
      - mongo 



  notes_v2:
    build: ./notes
    container_name: notes_v2
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, urllib.request; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/health').status==200 else sys.exit(1)"]
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on : 
      - mongo 


  # --------------------
  # ASSETS SERVICE
  # --------------------
  assets:
    build: ./assets
    container_name: assets_service

    volumes:
      - ./static:/main/app/static
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, urllib.request; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/health').status==200 else sys.exit(1)"]
      interval: 10s
      timeout: 3s
      retries: 3




  # --------------------
  # POSTGRES
  # --------------------
  postgres:
    image: postgres:16
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  # --------------------
  # MONGO
  # --------------------
  mongo:
    image: mongo:7
